# Generated by Django 5.1.3 on 2024-12-04 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ('title',), 'verbose_name_plural': 'Books'},
        ),
    ]
