# Generated by Django 5.1.3 on 2024-12-05 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pk', '0003_authorreverse_imagesmodels_booksreverse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagesmodels',
            options={'verbose_name_plural': 'ImagesModels'},
        ),
    ]
